# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("800x500")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 500,
    width = 800,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=133.0,
    y=422.0,
    width=151.0,
    height=37.0
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    118.5,
    146.0,
    image=entry_image_1
)
entry_1 = Entry(bd=0, bg="#F7F7F7", highlightthickness=0)
entry_1.place(
    x=39.0,
    y=126.0,
    width=159.0,
    height=38.0
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    118.5,
    303.0,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#F7F7F7",
    highlightthickness=0
)
entry_2.place(
    x=39.0,
    y=283.0,
    width=159.0,
    height=38.0
)

entry_image_3 = PhotoImage(
    file=relative_to_assets("entry_3.png"))
entry_bg_3 = canvas.create_image(
    118.5,
    227.0,
    image=entry_image_3
)
entry_3 = Entry(
    bd=0,
    bg="#F7F7F7",
    highlightthickness=0
)
entry_3.place(
    x=39.0,
    y=207.0,
    width=159.0,
    height=38.0
)

entry_image_4 = PhotoImage(
    file=relative_to_assets("entry_4.png"))
entry_bg_4 = canvas.create_image(
    118.5,
    384.0,
    image=entry_image_4
)
entry_4 = Entry(
    bd=0,
    bg="#F7F7F7",
    highlightthickness=0
)
entry_4.place(
    x=39.0,
    y=364.0,
    width=159.0,
    height=38.0
)

entry_image_5 = PhotoImage(
    file=relative_to_assets("entry_5.png"))
entry_bg_5 = canvas.create_image(
    301.5,
    146.0,
    image=entry_image_5
)
entry_5 = Entry(
    bd=0,
    bg="#F7F7F7",
    highlightthickness=0
)
entry_5.place(
    x=222.0,
    y=126.0,
    width=159.0,
    height=38.0
)

entry_image_6 = PhotoImage(
    file=relative_to_assets("entry_6.png"))
entry_bg_6 = canvas.create_image(
    301.5,
    303.0,
    image=entry_image_6
)
entry_6 = Entry(
    bd=0,
    bg="#F7F7F7",
    highlightthickness=0
)
entry_6.place(
    x=222.0,
    y=283.0,
    width=159.0,
    height=38.0
)

entry_image_7 = PhotoImage(
    file=relative_to_assets("entry_7.png"))
entry_bg_7 = canvas.create_image(
    301.5,
    227.0,
    image=entry_image_7
)
entry_7 = Entry(
    bd=0,
    bg="#F7F7F7",
    highlightthickness=0
)
entry_7.place(
    x=222.0,
    y=207.0,
    width=159.0,
    height=38.0
)

entry_image_8 = PhotoImage(
    file=relative_to_assets("entry_8.png"))
entry_bg_8 = canvas.create_image(
    301.5,
    384.0,
    image=entry_image_8
)
entry_8 = Entry(
    bd=0,
    bg="#F7F7F7",
    highlightthickness=0
)
entry_8.place(
    x=222.0,
    y=364.0,
    width=159.0,
    height=38.0
)

canvas.create_text(
    102.0,
    108.0,
    anchor="nw",
    text="Port",
    fill="#191919",
    font=("Inter SemiBold", 15 * -1)
)

canvas.create_text(
    438.0,
    237.0,
    anchor="nw",
    text="Sample Optical Pow",
    fill="#191919",
    font=("Inter SemiBold", 16 * -1)
)

canvas.create_text(
    437.0,
    157.0,
    anchor="nw",
    text="Horizontal Voltage 2",
    fill="#191919",
    font=("Inter SemiBold", 16 * -1)
)

canvas.create_text(
    444.0,
    76.0,
    anchor="nw",
    text="Horizontal Voltage",
    fill="#191919",
    font=("Inter SemiBold", 16 * -1)
)

canvas.create_text(
    643.0,
    236.0,
    anchor="nw",
    text="CurrDetDiffVolt",
    fill="#191919",
    font=("Inter SemiBold", 16 * -1)
)

canvas.create_text(
    632.0,
    157.0,
    anchor="nw",
    text="Vertical Voltage 2",
    fill="#191919",
    font=("Inter SemiBold", 16 * -1)
)

canvas.create_text(
    639.0,
    76.0,
    anchor="nw",
    text="Vertical Voltage",
    fill="#191919",
    font=("Inter SemiBold", 16 * -1)
)

canvas.create_text(
    53.0,
    187.0,
    anchor="nw",
    text="Horizontal Voltage",
    fill="#191919",
    font=("Inter SemiBold", 15 * -1)
)

canvas.create_text(
    47.0,
    265.0,
    anchor="nw",
    text="Horizontal Voltage 2",
    fill="#191919",
    font=("Inter SemiBold", 15 * -1)
)

canvas.create_text(
    46.0,
    343.0,
    anchor="nw",
    text="Sample Optical Pow",
    fill="#191919",
    font=("Inter SemiBold", 15 * -1)
)

canvas.create_text(
    244.0,
    187.0,
    anchor="nw",
    text="Vertical Voltage",
    fill="#191919",
    font=("Inter SemiBold", 15 * -1)
)

canvas.create_text(
    237.0,
    265.0,
    anchor="nw",
    text="Vertical Voltage 2",
    fill="#191919",
    font=("Inter SemiBold", 15 * -1)
)

canvas.create_text(
    245.0,
    343.0,
    anchor="nw",
    text="CurrDetDiffVolt",
    fill="#191919",
    font=("Inter SemiBold", 15 * -1)
)

canvas.create_text(
    268.0,
    108.0,
    anchor="nw",
    text="File Path",
    fill="#191919",
    font=("Inter SemiBold", 15 * -1)
)

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    613.0,
    398.0,
    image=image_image_1
)

canvas.create_text(
    442.0,
    295.0,
    anchor="nw",
    text="Output Log",
    fill="#191919",
    font=("Inter SemiBold", 17 * -1)
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    209.0,
    280.0,
    image=image_image_2
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    515.0,
    48.0,
    image=image_image_3
)

image_image_4 = PhotoImage(
    file=relative_to_assets("image_4.png"))
image_4 = canvas.create_image(
    514.0,
    130.0,
    image=image_image_4
)

image_image_5 = PhotoImage(
    file=relative_to_assets("image_5.png"))
image_5 = canvas.create_image(
    514.0,
    130.0,
    image=image_image_5
)

image_image_6 = PhotoImage(
    file=relative_to_assets("image_6.png"))
image_6 = canvas.create_image(
    514.0,
    212.0,
    image=image_image_6
)

image_image_7 = PhotoImage(
    file=relative_to_assets("image_7.png"))
image_7 = canvas.create_image(
    703.0,
    48.0,
    image=image_image_7
)

image_image_8 = PhotoImage(
    file=relative_to_assets("image_8.png"))
image_8 = canvas.create_image(
    702.0,
    130.0,
    image=image_image_8
)

image_image_9 = PhotoImage(
    file=relative_to_assets("image_9.png"))
image_9 = canvas.create_image(
    702.0,
    130.0,
    image=image_image_9
)

image_image_10 = PhotoImage(
    file=relative_to_assets("image_10.png"))
image_10 = canvas.create_image(
    701.0,
    212.0,
    image=image_image_10
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=12.0,
    y=25.0,
    width=395.0,
    height=51.0
)
window.resizable(False, False)
window.mainloop()